steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - VITE_API_URL=$_VITE_API_URL
      - --build-arg
      - VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY
      - --build-arg
      - VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN
      - --build-arg
      - VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID
      - --build-arg
      - VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID
      - -t
      - gcr.io/$PROJECT_ID/market-frontend
      - .

images:
  - gcr.io/$PROJECT_ID/market-frontend

substitutions:
  _VITE_API_URL: ""
  _VITE_FIREBASE_API_KEY: ""
  _VITE_FIREBASE_AUTH_DOMAIN: ""
  _VITE_FIREBASE_PROJECT_ID: ""
  _VITE_FIREBASE_APP_ID: ""
